### ISSUE TITLE
Player Count Increase Stats

### ISSUE THREAD

**Issue by Demonasus** [azerothcore/mod-autobalance#107]
I always wondered, which part of the code explicitly controls how the increase works on each player inside an instance. For example, right now 1 player inside NPC HP is 5000 , 2nd player enters NPC HP is 10000 and so on. Is there a part of formula that can be modified to control or modify that increase? so it doesn't double the stats but instead maybe the increase could be 1.5 or 1.2 etc?

So far any changes I made to formula seems to do the trick but not every single time. Anyone here has any info?

**Comment by BarbzYHOOL** [comment]
this module should be heavily configurable :(

**Comment by kanbie** [comment]
Was there a level delta such that player 2 was higher level? The dynamic level scaling is going to apply and throw of the values you are expecting to see.

Visit the conf file and disable the dynamic scalier for levels and you should see behavior were only the curve is dictating the stats.

**Comment by kjack9** [comment]
You should edit the fields in the config file rather than messing with the formula source directly. The latest versions of `mod-autobalance` have extensive notes on each setting explaining what they do and how to use them. You can also use the [Interactive Inflection Point Spreadsheet](https://docs.google.com/spreadsheets/d/100cmKIJIjCZ-ncWd0K9ykO8KUgwFTcwg4h2nfE_UeCc/copy) to simulate various scaling settings until you are happy with where the difficulty falls.
