### ISSUE TITLE
Apparent contradiction in InflectionPoint config

### ISSUE THREAD

**Issue by arlyon** [azerothcore/mod-autobalance#108]
Hello, from the config file:

https://github.com/azerothcore/mod-autobalance/blob/007792207ca056e4828306f2cff1da1986d6414a/conf/AutoBalance.conf.dist#L25-L37

Line 27 says that lower values imply higher difficulty, however on line 34-35 the example implies a reverse correlation. If 0.5 means that health and mana scale linearly with party size, then I would assume that a value of 0.8 would mean half health with _more_ than 20 people not _less_, however in the example the proportion of 'health per person' nearly doubled.

```
People | Inflection | Health | Health per Person
40     | 0.5        | 4000   | 100
20     | 0.5        | 2000   | 100
12     | 0.8        | 2000   | 166.67
```

The table of values is my interpretation of the example and it seems clear that putting the inflection higher means more health per person and by extension a higher difficulty. From testing, however, it seems that the description is in fact correct it is just the example that is misleading.

Cheers

Alex

**Comment by kjack9** [comment]
Thank you for this report. The InflectionPoint system and the surrounding descriptors in the config file were completely reworked in https://github.com/azerothcore/mod-autobalance/commit/c23e5ab38b262a8c1f69eb61e616cc32400b0646 as well as later commits.

This spreadsheet should be of particular interest to you:
https://docs.google.com/spreadsheets/d/100cmKIJIjCZ-ncWd0K9ykO8KUgwFTcwg4h2nfE_UeCc/copy

If you still feel like the issues raised in this request are valid and need addressing, please re-open the request with additional details. Otherwise, I'm going to consider it fixed by https://github.com/azerothcore/mod-autobalance/commit/c23e5ab38b262a8c1f69eb61e616cc32400b0646 .

**Comment by arlyon** [comment]
Love to see it. Thanks for taking the time and for this great plugin.
