### ISSUE TITLE
Bug: valithria dreamwalker icc appears with 100% life

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/mod-autobalance#164]
### Current Behaviour

the dragon appears with all her life with autobalance

![278090944-c3df8e29-2271-4adb-adf1-1a457ce1704a](https://github.com/azerothcore/mod-autobalance/assets/88008285/17ba1af8-9235-4cfa-8df4-4ffaa75528cb)

### Expected Behaviour

She should have 1/2 life and we must cure her 100%

### Steps to reproduce the problem

.

### AC rev. hash/commit

41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

windows 10

### Custom changes or Modules

mod-autobalance

**Comment by kjack9** [comment]
Confirmed, I will work on this.

**Comment by kjack9** [comment]
I think this is a side effect of how the boss script is written.

AutoBalance is correctly adjusting the creature health when scaling:

```css
AutoBalance::getStatModifiers: Map Icecrown Citadel (631-4) | Creature Valithria Dreamwalker (83->83) | 10 Player Normal Boss
<...>
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | ---------- HEALTH MULTIPLIER ----------
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | HealthMultiplier: (0.060558204) = defaultMultiplier (0.067286894) * statMod_global (1) * statMod_health (0.9)
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | scaledHealthMultiplier (0.060558204) = healthMultiplier (0.060558204)
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | origHealth (12000007) = origCreatureBaseStats->GenerateHealth(creatureTemplate)
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | newFinalHealth (726699) = origHealth (12000007) * HealthMultiplier (0.060558204)
<...>
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | ---------- FINAL STATS ----------
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Valithria Dreamwalker (83) | Health (6000003/12000007 50.0%) -> (363349/726699 50.0%)
```

However, the script is adjusting the _spawnHealth based on the creature template.

https://github.com/azerothcore/azerothcore-wotlk/blob/41dba1affbb5a24457a894bf3d503f4aa6303a1b/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp#L297-L299

This will require an update to the boss script in the core, which I plan to work on. Shouldn't be crazy complicated, just need to adjust the initial health based on the creature's max health in the world rather than in the database.

**Comment by kjack9** [comment]
Confirmed, that's definitely what it is. Working on a PR to the core to make the script more module-friendly.

**Comment by kjack9** [comment]
Please update to the latest AzerothCore revision and let me know if this is still an issue.

**Comment by Fireevil** [comment]
![image](https://github.com/azerothcore/mod-autobalance/assets/88008285/0bab5413-e88f-4b7f-9f46-35aff518c143)

Work fine with autobalance
