### ISSUE TITLE
QUESTION: Difference to mod-solocraft?

### ISSUE THREAD

**Issue by TobiMiller** [azerothcore/mod-autobalance#38]
Hey,

what's the difference to mod-solocraft? i see that there is a lot more development going on here.  i might misunderstand the description and both have a separate right to exist.

best regards

**Comment by Yehonal** [comment]
we discussed it here: https://github.com/azerothcore/mod-solocraft/issues/5#issuecomment-524444681

solocraft boost the player and it's for single player

the autobalance module instead modifies the stats of the creatures in a flexible way, so you can play solo or with X other players, it doesn't matter, the system will fix the difficulty dynamically

**Comment by BarbzYHOOL** [comment]
and what happens when there are 2 players of different level ? xD

autobalance allows to have a "challenge" in lower level dungeons too it's cool imo

**Comment by TobiMiller** [comment]
thanks. i have to play around with the config. actually it was very easy to go through an instance. it should be still a challenge ;)

**Comment by BarbzYHOOL** [comment]
i also tried lvl 10 going into wailing caverns and it was very easy

**Comment by Yehonal** [comment]
Consider that when you go with 5 level 10 in wailing caverns, it's very
easy too :) you can benchmark it, just try to kill the same creature with 5
ppl without autobalance and then again on solo with autobalance. You should
see a small difference. Otherwise, I can check the formula again

Anyway, I don't suggest to change the inflection conf, but the minplayers
instead

**Comment by Yehonal** [comment]
AutoBalance.playerCountDifficultyOffset=0  ->
AutoBalance.playerCountDifficultyOffset=1

In this way, the autobalance will scale as you're always with another
player even though you're alone. You can increase to your preferred value

**Comment by BarbzYHOOL** [comment]
> Consider that when you go with 5 level 10 in wailing caverns, it's very easy too :) you can benchmark it, just try to kill the same creature with 5 ppl without autobalance and then again on solo with autobalance. You should see a small difference. Otherwise, I can check the formula again > Anyway, I don't suggest to change the inflection conf, but the minplayers instead


good point :P

**Comment by BarbzYHOOL** [comment]
just retried, a level 14 elite has 100 HP and gets one shot by any spell, 100hp is probably the HP of a lvl 1 mob

**Comment by BarbzYHOOL** [comment]
and damage is 15 instead of 30 for a non elite similar mob

**Comment by BarbzYHOOL** [comment]
@Yehonal 

Ok i made some serious tests in wailing cavern with default settings.
I took a green gear on my lvl 16 druid, and then i pull two elite lvl 18

They do 3-4 damage with each attack instead of 30 to my bear form.
An enemy druid who casts a spell does 8 damage instead of 70
They have 100 HP which means I can kill them in 4 attacks or something like that.

I really feel like something is off. Of course, I can change the playeroffset from 0 to 1 but then it's still super easy. I can change to 3 but then what happens for a group of 4 people?

I can also change these rates:

```
AutoBalance.rate.global = 2.0
AutoBalance.rate.health = 1.0
AutoBalance.rate.mana   = 1.0
AutoBalance.rate.armor  = 1.0
AutoBalance.rate.damage = 2.0
```

**Comment by Yehonal** [comment]
Those rates shouldn't be touched because it implies that even with a full party the difficulty is doubled.

The playeroffset is the best way to do it if you want to increase the overall difficulty without touch the normal experience with a full party, because it's a simply offset, when the number of players is lower of the offset, the autobalance uses the same values as you are with that "offset". When the number of players is equal or higher, then the autobalance will just scale in relation of the number of the players.

Anyway, the game experience is different because you must consider many cases...it's not just a matter of a single battle but the capability of a single player to complete the entire instance without die and in the same time of a 5 player group (talking about a working dungeon without particular mechanics)

For example, when you're with 5 people you can manage more mobs, you can be healed easier and faster, you can recover while other people are fighting etc.

In solo you cannot do it

**Comment by BarbzYHOOL** [comment]
the player offset I don't see any interest in it

so like everybody else (4 users told me so) I modified the inflection points

but my tests also showed me that all low level dungeons bosses have wrong stats in creature_template (at least for damage) so that really doesn't help in testing
