### ISSUE TITLE
Enrage timers should be proportional (or configurable)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-autobalance#81]
A lot of bosses have enrage timers, maybe we could have a slight increase when there are less players? something proportional

Not sure if possible with the current bosses (because the enrage timers are probably hardcoded in cpp) and not sure if a good idea, but considerng the actual module is not working for many complex bosses, it seems needed at the moment

**Comment by kjack9** [comment]
Hopefully some of those outliers have been resolved, especially after #125. I also have intentions to start modifying the damage caused by non-creature sources in an upcoming release. Regardless, I'd much rather get the scaling fixed properly rather than working around any issues by changing the scaling timers.
